# File generated by stainful — DO NOT EDIT.
"""hermes — generated by stainful (the open-source Stainless)."""

from __future__ import annotations

from ._client import AsyncHermesSDK, HermesSDK
from ._core._exceptions import (
    APIConnectionError,
    APIError,
    APIResponseValidationError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    InternalServerError,
    InvalidWebhookSignatureError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    UnprocessableEntityError,
)
from ._core._response import APIResponse
from ._core._sentinels import NOT_GIVEN, NotGiven, Omit, not_given, omit

HermesSDKError = APIError
HermesSDKAPIResponse = APIResponse

__all__ = ['HermesSDK', 'AsyncHermesSDK', 'HermesSDKError', 'HermesSDKAPIResponse', 'APIResponse', 'NotGiven', 'not_given', 'NOT_GIVEN', 'Omit', 'omit', 'APIConnectionError', 'APIError', 'APIResponseValidationError', 'APIStatusError', 'APITimeoutError', 'AuthenticationError', 'BadRequestError', 'ConflictError', 'InternalServerError', 'InvalidWebhookSignatureError', 'NotFoundError', 'PermissionDeniedError', 'RateLimitError', 'UnprocessableEntityError']
