# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

import os

import httpx

from ._core._base_client import AsyncAPIClient, SyncAPIClient
from ._core._sentinels import NotGiven, not_given
from . import resources

__all__ = ["HermesSDK", "AsyncHermesSDK"]

_DEFAULT_BASE_URL = "http://localhost:8643"


class HermesSDK(SyncAPIClient):
    health: resources.HealthResource
    capabilities: resources.CapabilitiesResource
    chat_completions: resources.ChatCompletionsResource
    runs: resources.RunsResource
    runs_events: resources.RunsEventsResource
    runs_approval: resources.RunsApprovalResource

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | httpx.URL | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
        max_retries: int = 2,
        http_client: httpx.Client | None = None,
    ) -> None:
        if api_key is None:
            api_key = os.environ.get("HERMES_API_KEY")
        if api_key is None:
            raise ValueError(
                "The api_key client option must be set either by passing api_key "
                "to the client or by setting the HERMES_API_KEY environment variable"
            )
        super().__init__(
            base_url=base_url or os.environ.get("HERMES_BASE_URL") or _DEFAULT_BASE_URL,
            timeout=timeout,
            max_retries=max_retries,
            http_client=http_client,
            auth_headers={"Authorization": f"Bearer {api_key}"},
        )
        self.health = resources.HealthResource(self)
        self.capabilities = resources.CapabilitiesResource(self)
        self.chat_completions = resources.ChatCompletionsResource(self)
        self.runs = resources.RunsResource(self)
        self.runs_events = resources.RunsEventsResource(self)
        self.runs_approval = resources.RunsApprovalResource(self)


class AsyncHermesSDK(AsyncAPIClient):
    health: resources.AsyncHealthResource
    capabilities: resources.AsyncCapabilitiesResource
    chat_completions: resources.AsyncChatCompletionsResource
    runs: resources.AsyncRunsResource
    runs_events: resources.AsyncRunsEventsResource
    runs_approval: resources.AsyncRunsApprovalResource

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str | httpx.URL | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
        max_retries: int = 2,
        http_client: httpx.AsyncClient | None = None,
    ) -> None:
        if api_key is None:
            api_key = os.environ.get("HERMES_API_KEY")
        if api_key is None:
            raise ValueError(
                "The api_key client option must be set either by passing api_key "
                "to the client or by setting the HERMES_API_KEY environment variable"
            )
        super().__init__(
            base_url=base_url or os.environ.get("HERMES_BASE_URL") or _DEFAULT_BASE_URL,
            timeout=timeout,
            max_retries=max_retries,
            http_client=http_client,
            auth_headers={"Authorization": f"Bearer {api_key}"},
        )
        self.health = resources.AsyncHealthResource(self)
        self.capabilities = resources.AsyncCapabilitiesResource(self)
        self.chat_completions = resources.AsyncChatCompletionsResource(self)
        self.runs = resources.AsyncRunsResource(self)
        self.runs_events = resources.AsyncRunsEventsResource(self)
        self.runs_approval = resources.AsyncRunsApprovalResource(self)
