# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class ChatCompletionCreateResponseChoiceMessage(BaseModel):
    role: Literal['system', 'user', 'assistant']
    content: str


class ChatCompletionCreateResponseChoice(BaseModel):
    index: int
    message: ChatCompletionCreateResponseChoiceMessage
    finish_reason: Optional[Literal['stop', 'length', 'content_filter']]


class ChatCompletionCreateResponseUsage(BaseModel):
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None


class ChatCompletionCreateResponse(BaseModel):
    id: str
    object: Literal['chat.completion']
    created: int
    model: Optional[str] = None
    choices: List[ChatCompletionCreateResponseChoice]
    usage: Optional[ChatCompletionCreateResponseUsage] = None


class ChatCompletionCreateEventChoiceDelta(BaseModel):
    role: Optional[str] = None
    content: Optional[str] = None


class ChatCompletionCreateEventChoice(BaseModel):
    index: int
    delta: ChatCompletionCreateEventChoiceDelta
    finish_reason: Optional[str] = None


class ChatCompletionCreateEvent(BaseModel):
    id: str
    object: Literal['chat.completion.chunk']
    created: int
    model: Optional[str] = None
    choices: List[ChatCompletionCreateEventChoice]
