# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property
from typing import Literal, overload

import httpx

from hyver._core._models import to_jsonable
from hyver._core._request_options import make_request_options
from hyver._core._resource import AsyncAPIResource, SyncAPIResource
from hyver._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from hyver._core._sentinels import NotGiven, not_given
from hyver._core._streaming import AsyncStream, Stream
from hyver._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from hyver.types import ChatCompletionCreateEvent, ChatCompletionCreateParamsMessages, ChatCompletionCreateResponse

__all__ = ["ChatCompletionsResource", "AsyncChatCompletionsResource"]


class ChatCompletionsResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ChatCompletionsResourceWithRawResponse:
        return ChatCompletionsResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ChatCompletionsResourceWithStreamingResponse:
        return ChatCompletionsResourceWithStreamingResponse(self)

    @overload
    def create(
        self,
        *,
        messages: list[ChatCompletionCreateParamsMessages],
        stream: Literal[False] = False,
        model: str | NotGiven = not_given,
        temperature: float | NotGiven = not_given,
        max_tokens: int | NotGiven = not_given,
        top_p: float | NotGiven = not_given,
        stop: list[str] | str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ChatCompletionCreateResponse: ...

    @overload
    def create(
        self,
        *,
        messages: list[ChatCompletionCreateParamsMessages],
        stream: Literal[True],
        model: str | NotGiven = not_given,
        temperature: float | NotGiven = not_given,
        max_tokens: int | NotGiven = not_given,
        top_p: float | NotGiven = not_given,
        stop: list[str] | str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Stream[ChatCompletionCreateEvent]: ...

    def create(
        self,
        *,
        messages: list[ChatCompletionCreateParamsMessages],
        stream: bool = False,
        model: str | NotGiven = not_given,
        temperature: float | NotGiven = not_given,
        max_tokens: int | NotGiven = not_given,
        top_p: float | NotGiven = not_given,
        stop: list[str] | str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ChatCompletionCreateResponse | Stream[ChatCompletionCreateEvent]:
        """OpenAI-compatible chat completion endpoint. Requests are routed through
        a model routing proxy that selects the appropriate model based on
        complexity and tier, then forwarded to LiteLLM."""
        _body = {
            "model": model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": stream,
            "top_p": top_p,
            "stop": stop,
        }
        _body = {k: v for k, v in _body.items() if v is not not_given}
        return self._post(
            "/v1/chat/completions",
            body=to_jsonable(_body),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=ChatCompletionCreateEvent if stream else ChatCompletionCreateResponse,
            stream=stream,
            stream_cls=Stream,
        )


class AsyncChatCompletionsResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncChatCompletionsResourceWithRawResponse:
        return AsyncChatCompletionsResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncChatCompletionsResourceWithStreamingResponse:
        return AsyncChatCompletionsResourceWithStreamingResponse(self)

    @overload
    async def create(
        self,
        *,
        messages: list[ChatCompletionCreateParamsMessages],
        stream: Literal[False] = False,
        model: str | NotGiven = not_given,
        temperature: float | NotGiven = not_given,
        max_tokens: int | NotGiven = not_given,
        top_p: float | NotGiven = not_given,
        stop: list[str] | str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ChatCompletionCreateResponse: ...

    @overload
    async def create(
        self,
        *,
        messages: list[ChatCompletionCreateParamsMessages],
        stream: Literal[True],
        model: str | NotGiven = not_given,
        temperature: float | NotGiven = not_given,
        max_tokens: int | NotGiven = not_given,
        top_p: float | NotGiven = not_given,
        stop: list[str] | str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncStream[ChatCompletionCreateEvent]: ...

    async def create(
        self,
        *,
        messages: list[ChatCompletionCreateParamsMessages],
        stream: bool = False,
        model: str | NotGiven = not_given,
        temperature: float | NotGiven = not_given,
        max_tokens: int | NotGiven = not_given,
        top_p: float | NotGiven = not_given,
        stop: list[str] | str | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ChatCompletionCreateResponse | AsyncStream[ChatCompletionCreateEvent]:
        """OpenAI-compatible chat completion endpoint. Requests are routed through
        a model routing proxy that selects the appropriate model based on
        complexity and tier, then forwarded to LiteLLM."""
        _body = {
            "model": model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": stream,
            "top_p": top_p,
            "stop": stop,
        }
        _body = {k: v for k, v in _body.items() if v is not not_given}
        return await self._post(
            "/v1/chat/completions",
            body=to_jsonable(_body),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=ChatCompletionCreateEvent if stream else ChatCompletionCreateResponse,
            stream=stream,
            stream_cls=AsyncStream,
        )


class ChatCompletionsResourceWithRawResponse:
    def __init__(self, chat_completions: ChatCompletionsResource) -> None:
        self.create = to_raw_response_wrapper(chat_completions.create)


class AsyncChatCompletionsResourceWithRawResponse:
    def __init__(self, chat_completions: AsyncChatCompletionsResource) -> None:
        self.create = async_to_raw_response_wrapper(chat_completions.create)


class ChatCompletionsResourceWithStreamingResponse:
    def __init__(self, chat_completions: ChatCompletionsResource) -> None:
        self.create = to_streamed_response_wrapper(chat_completions.create)


class AsyncChatCompletionsResourceWithStreamingResponse:
    def __init__(self, chat_completions: AsyncChatCompletionsResource) -> None:
        self.create = async_to_streamed_response_wrapper(chat_completions.create)
