# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property
from typing import Literal
from urllib.parse import quote

import httpx

from hyver._core._models import to_jsonable
from hyver._core._request_options import make_request_options
from hyver._core._resource import AsyncAPIResource, SyncAPIResource
from hyver._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from hyver._core._sentinels import NotGiven, not_given
from hyver._core._types import Body, FileTypes, Headers, Query  # noqa: F401

__all__ = ["RunsApprovalResource", "AsyncRunsApprovalResource"]


class RunsApprovalResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> RunsApprovalResourceWithRawResponse:
        return RunsApprovalResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> RunsApprovalResourceWithStreamingResponse:
        return RunsApprovalResourceWithStreamingResponse(self)

    def submit(
        self,
        *,
        run_id: str,
        choice: Literal["once", "session", "always", "deny", "approve", "approved", "allow"],
        all: bool | NotGiven = not_given,
        resolve_all: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> object:
        """Approves or rejects a pending action during a run that has
        human-in-the-loop control enabled."""
        _body = {
            "choice": choice,
            "all": all,
            "resolve_all": resolve_all,
        }
        _body = {k: v for k, v in _body.items() if v is not not_given}
        return self._post(
            f"/v1/runs/{quote(run_id, safe='')}/approval",
            body=to_jsonable(_body),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=object,
        )


class AsyncRunsApprovalResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncRunsApprovalResourceWithRawResponse:
        return AsyncRunsApprovalResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncRunsApprovalResourceWithStreamingResponse:
        return AsyncRunsApprovalResourceWithStreamingResponse(self)

    async def submit(
        self,
        *,
        run_id: str,
        choice: Literal["once", "session", "always", "deny", "approve", "approved", "allow"],
        all: bool | NotGiven = not_given,
        resolve_all: bool | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> object:
        """Approves or rejects a pending action during a run that has
        human-in-the-loop control enabled."""
        _body = {
            "choice": choice,
            "all": all,
            "resolve_all": resolve_all,
        }
        _body = {k: v for k, v in _body.items() if v is not not_given}
        return await self._post(
            f"/v1/runs/{quote(run_id, safe='')}/approval",
            body=to_jsonable(_body),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=object,
        )


class RunsApprovalResourceWithRawResponse:
    def __init__(self, runs_approval: RunsApprovalResource) -> None:
        self.submit = to_raw_response_wrapper(runs_approval.submit)


class AsyncRunsApprovalResourceWithRawResponse:
    def __init__(self, runs_approval: AsyncRunsApprovalResource) -> None:
        self.submit = async_to_raw_response_wrapper(runs_approval.submit)


class RunsApprovalResourceWithStreamingResponse:
    def __init__(self, runs_approval: RunsApprovalResource) -> None:
        self.submit = to_streamed_response_wrapper(runs_approval.submit)


class AsyncRunsApprovalResourceWithStreamingResponse:
    def __init__(self, runs_approval: AsyncRunsApprovalResource) -> None:
        self.submit = async_to_streamed_response_wrapper(runs_approval.submit)
