# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property
from urllib.parse import quote

import httpx

from hyver._core._models import to_jsonable
from hyver._core._request_options import make_request_options
from hyver._core._resource import AsyncAPIResource, SyncAPIResource
from hyver._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from hyver._core._sentinels import NotGiven, not_given
from hyver._core._types import Body, FileTypes, Headers, Query  # noqa: F401
from hyver.types import (
    RunCreateParamsConversationHistory,
    RunCreateParamsImages,
    RunCreateParamsMetadata,
    RunCreateResponse,
)

__all__ = ["RunsResource", "AsyncRunsResource"]


class RunsResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> RunsResourceWithRawResponse:
        return RunsResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> RunsResourceWithStreamingResponse:
        return RunsResourceWithStreamingResponse(self)

    def create(
        self,
        *,
        input: str,
        session_id: str,
        instructions: str | NotGiven = not_given,
        images: list[RunCreateParamsImages] | NotGiven = not_given,
        conversation_history: list[RunCreateParamsConversationHistory] | NotGiven = not_given,
        metadata: RunCreateParamsMetadata | NotGiven = not_given,
        tools: list[str] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> RunCreateResponse:
        """Creates a new agent run with the given input and configuration. Returns
        a run ID that can be used to stream events, submit approvals, or stop
        the run."""
        _body = {
            "input": input,
            "session_id": session_id,
            "instructions": instructions,
            "images": images,
            "conversation_history": conversation_history,
            "metadata": metadata,
            "tools": tools,
        }
        _body = {k: v for k, v in _body.items() if v is not not_given}
        return self._post(
            "/v1/runs",
            body=to_jsonable(_body),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=RunCreateResponse,
        )

    def stop(
        self,
        *,
        run_id: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> object:
        """Signals the runtime to stop the specified run."""
        return self._post(
            f"/v1/runs/{quote(run_id, safe='')}/stop",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=object,
        )


class AsyncRunsResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncRunsResourceWithRawResponse:
        return AsyncRunsResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncRunsResourceWithStreamingResponse:
        return AsyncRunsResourceWithStreamingResponse(self)

    async def create(
        self,
        *,
        input: str,
        session_id: str,
        instructions: str | NotGiven = not_given,
        images: list[RunCreateParamsImages] | NotGiven = not_given,
        conversation_history: list[RunCreateParamsConversationHistory] | NotGiven = not_given,
        metadata: RunCreateParamsMetadata | NotGiven = not_given,
        tools: list[str] | NotGiven = not_given,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> RunCreateResponse:
        """Creates a new agent run with the given input and configuration. Returns
        a run ID that can be used to stream events, submit approvals, or stop
        the run."""
        _body = {
            "input": input,
            "session_id": session_id,
            "instructions": instructions,
            "images": images,
            "conversation_history": conversation_history,
            "metadata": metadata,
            "tools": tools,
        }
        _body = {k: v for k, v in _body.items() if v is not not_given}
        return await self._post(
            "/v1/runs",
            body=to_jsonable(_body),
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=RunCreateResponse,
        )

    async def stop(
        self,
        *,
        run_id: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> object:
        """Signals the runtime to stop the specified run."""
        return await self._post(
            f"/v1/runs/{quote(run_id, safe='')}/stop",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=object,
        )


class RunsResourceWithRawResponse:
    def __init__(self, runs: RunsResource) -> None:
        self.create = to_raw_response_wrapper(runs.create)
        self.stop = to_raw_response_wrapper(runs.stop)


class AsyncRunsResourceWithRawResponse:
    def __init__(self, runs: AsyncRunsResource) -> None:
        self.create = async_to_raw_response_wrapper(runs.create)
        self.stop = async_to_raw_response_wrapper(runs.stop)


class RunsResourceWithStreamingResponse:
    def __init__(self, runs: RunsResource) -> None:
        self.create = to_streamed_response_wrapper(runs.create)
        self.stop = to_streamed_response_wrapper(runs.stop)


class AsyncRunsResourceWithStreamingResponse:
    def __init__(self, runs: AsyncRunsResource) -> None:
        self.create = async_to_streamed_response_wrapper(runs.create)
        self.stop = async_to_streamed_response_wrapper(runs.stop)
