# File generated by stainful — DO NOT EDIT (manual fixes applied for run_id param + SSE streaming).
from __future__ import annotations

from functools import cached_property
from typing import Annotated
from urllib.parse import quote

import httpx
from pydantic import Field

from hyver._core._request_options import make_request_options
from hyver._core._resource import AsyncAPIResource, SyncAPIResource
from hyver._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from hyver._core._sentinels import NotGiven, not_given
from hyver._core._streaming import AsyncStream, Stream
from hyver._core._types import Body, Headers, Query
from hyver.types import (
    ApprovalRequestEvent,
    ApprovalRequiredEvent,
    ApprovalRespondedEvent,
    ContentDeltaEvent,
    DoneEvent,
    ErrorEvent,
    OutputItemAddedEvent,
    OutputItemDoneEvent,
    ReasoningEvent,
    ResponseCompletedEvent,
    ResponseCreatedEvent,
    ResponseFailedEvent,
    RunCancelledEvent,
    RunCompletedEvent,
    RunFailedEvent,
    ToolCompletedEvent,
    ToolProgressEvent,
    ToolResultEvent,
    ToolStartedEvent,
    ToolStartEvent,
    UsageEvent,
)

__all__ = ["RunsEventsResource", "AsyncRunsEventsResource"]

_SSEEventUnion = Annotated[
    ApprovalRequestEvent | ApprovalRequiredEvent | ApprovalRespondedEvent | ContentDeltaEvent | DoneEvent | ErrorEvent | OutputItemAddedEvent | OutputItemDoneEvent | ReasoningEvent | ResponseCompletedEvent | ResponseCreatedEvent | ResponseFailedEvent | RunCancelledEvent | RunCompletedEvent | RunFailedEvent | ToolCompletedEvent | ToolProgressEvent | ToolResultEvent | ToolStartEvent | ToolStartedEvent | UsageEvent,
    Field(discriminator="event"),
]
_RawEvent = dict[str, object]
_SSEEvent = _SSEEventUnion | _RawEvent


class RunsEventsResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> RunsEventsResourceWithRawResponse:
        return RunsEventsResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> RunsEventsResourceWithStreamingResponse:
        return RunsEventsResourceWithStreamingResponse(self)

    def stream(
        self,
        *,
        run_id: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Stream[_SSEEvent]:
        """Opens a Server-Sent Events stream for the specified run. Events include
        content deltas, tool executions, reasoning steps, approval requests,
        usage statistics, and completion/failure signals."""
        return self._client._request(
            "GET",
            f"/v1/runs/{quote(run_id, safe='')}/events",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=_SSEEventUnion,
            stream=True,
            stream_cls=Stream,
        )


class AsyncRunsEventsResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncRunsEventsResourceWithRawResponse:
        return AsyncRunsEventsResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncRunsEventsResourceWithStreamingResponse:
        return AsyncRunsEventsResourceWithStreamingResponse(self)

    async def stream(
        self,
        *,
        run_id: str,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncStream[_SSEEvent]:
        """Opens a Server-Sent Events stream for the specified run. Events include
        content deltas, tool executions, reasoning steps, approval requests,
        usage statistics, and completion/failure signals."""
        return await self._client._request(
            "GET",
            f"/v1/runs/{quote(run_id, safe='')}/events",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=_SSEEventUnion,
            stream=True,
            stream_cls=AsyncStream,
        )


class RunsEventsResourceWithRawResponse:
    def __init__(self, runs_events: RunsEventsResource) -> None:
        self.stream = to_raw_response_wrapper(runs_events.stream)


class AsyncRunsEventsResourceWithRawResponse:
    def __init__(self, runs_events: AsyncRunsEventsResource) -> None:
        self.stream = async_to_raw_response_wrapper(runs_events.stream)


class RunsEventsResourceWithStreamingResponse:
    def __init__(self, runs_events: RunsEventsResource) -> None:
        self.stream = to_streamed_response_wrapper(runs_events.stream)


class AsyncRunsEventsResourceWithStreamingResponse:
    def __init__(self, runs_events: AsyncRunsEventsResource) -> None:
        self.stream = async_to_streamed_response_wrapper(runs_events.stream)
