# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from functools import cached_property
from typing import Dict

import httpx

from hermes._core._request_options import make_request_options
from hermes._core._resource import AsyncAPIResource, SyncAPIResource
from hermes._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from hermes._core._sentinels import NotGiven, not_given
from hermes._core._types import Body, FileTypes, Headers, Query  # noqa: F401

__all__ = ["CapabilitiesResource", "AsyncCapabilitiesResource"]


class CapabilitiesResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> CapabilitiesResourceWithRawResponse:
        return CapabilitiesResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> CapabilitiesResourceWithStreamingResponse:
        return CapabilitiesResourceWithStreamingResponse(self)

    def get(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Dict[str, object]:
        """Returns available runtime capabilities. Proxied directly to the Hermes
upstream service. No authentication required."""
        return self._get(
            f"/v1/capabilities",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=Dict[str, object],
        )


class AsyncCapabilitiesResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncCapabilitiesResourceWithRawResponse:
        return AsyncCapabilitiesResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncCapabilitiesResourceWithStreamingResponse:
        return AsyncCapabilitiesResourceWithStreamingResponse(self)

    async def get(
        self,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> Dict[str, object]:
        """Returns available runtime capabilities. Proxied directly to the Hermes
upstream service. No authentication required."""
        return await self._get(
            f"/v1/capabilities",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=Dict[str, object],
        )


class CapabilitiesResourceWithRawResponse:
    def __init__(self, capabilities: CapabilitiesResource) -> None:
        self.get = to_raw_response_wrapper(capabilities.get)


class AsyncCapabilitiesResourceWithRawResponse:
    def __init__(self, capabilities: AsyncCapabilitiesResource) -> None:
        self.get = async_to_raw_response_wrapper(capabilities.get)


class CapabilitiesResourceWithStreamingResponse:
    def __init__(self, capabilities: CapabilitiesResource) -> None:
        self.get = to_streamed_response_wrapper(capabilities.get)


class AsyncCapabilitiesResourceWithStreamingResponse:
    def __init__(self, capabilities: AsyncCapabilitiesResource) -> None:
        self.get = async_to_streamed_response_wrapper(capabilities.get)
