# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (
    Literal,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class ChatCompletionCreateResponseChoiceMessage(BaseModel):
    role: Literal["system", "user", "assistant"]
    content: str


class ChatCompletionCreateResponseChoice(BaseModel):
    index: int
    message: ChatCompletionCreateResponseChoiceMessage
    finish_reason: Literal["stop", "length", "content_filter"] | None


class ChatCompletionCreateResponseUsage(BaseModel):
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    total_tokens: int | None = None


class ChatCompletionCreateResponse(BaseModel):
    id: str
    object: Literal["chat.completion"]
    created: int
    model: str | None = None
    choices: list[ChatCompletionCreateResponseChoice]
    usage: ChatCompletionCreateResponseUsage | None = None


class ChatCompletionCreateEventChoiceDelta(BaseModel):
    role: str | None = None
    content: str | None = None


class ChatCompletionCreateEventChoice(BaseModel):
    index: int
    delta: ChatCompletionCreateEventChoiceDelta
    finish_reason: str | None = None


class ChatCompletionCreateEvent(BaseModel):
    id: str
    object: Literal["chat.completion.chunk"]
    created: int
    model: str | None = None
    choices: list[ChatCompletionCreateEventChoice]
