# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (
    Literal,
)

from pydantic import Field  # noqa: F401
from typing_extensions import Required, TypedDict  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class RunCreateParamsImages(BaseModel):
    base64: str
    mime_type: str = Field(alias="mimeType")
    file_name: str | None = Field(default=None, alias="fileName")
    size_bytes: int | None = Field(default=None, alias="sizeBytes")


class RunCreateParamsConversationHistory(BaseModel):
    role: Literal["user", "assistant", "system"]
    content: str


class RunCreateParamsMetadata(BaseModel):
    reasoning: bool | None = None
    search_enabled: bool | None = None
    human_control: bool | None = None


class RunCreateParams(TypedDict, total=False):
    input: Required[str]
    session_id: Required[str]
    instructions: str
    images: list[RunCreateParamsImages]
    conversation_history: list[RunCreateParamsConversationHistory]
    metadata: RunCreateParamsMetadata
    tools: list[str]
