# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated,
    Any,
    Dict,
    List,
    Literal,
    Optional,
    Union,
)
from typing_extensions import Required, TypedDict  # noqa: F401

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class RunsApprovalSubmitParams(TypedDict, total=False):
    choice: Required[Literal["once", "session", "always", "deny", "approve", "approved", "allow"]]
    all: bool
    resolve_all: bool
