# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated,
    Any,
    Dict,
    List,
    Literal,
    Optional,
    TypedDict,
    Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class ResponseCreatedEvent(BaseModel):
    event: Literal["response.created"]


class ContentDeltaEvent(BaseModel):
    event: Literal["response.output_text.delta", "message.delta"]
    delta: str


class OutputItemOutputVariant1(BaseModel):
    text: str | None = None


class OutputItem(BaseModel):
    type: Literal["function_call", "image", "function_call_output"]
    call_id: str | None = None
    name: str | None = None
    arguments: str | None = None
    url: str | None = None
    title: str | None = None
    output: list[OutputItemOutputVariant1] | str | None = None


class OutputItemAddedEvent(BaseModel):
    event: Literal["response.output_item.added"]
    item: OutputItem


class OutputItemDoneEvent(BaseModel):
    event: Literal["response.output_item.done"]
    item: OutputItem


class UsageInfo(BaseModel):
    input_tokens: int | None = None
    output_tokens: int | None = None
    total_tokens: int | None = None
    system_prompt_tokens: int | None = None


class ResponseCompletedEvent(BaseModel):
    event: Literal["response.completed"]
    usage: UsageInfo | None = None
    model: str | None = None
    session_id: str | None = None


class ResponseFailedEventError(BaseModel):
    message: str | None = None


class ResponseFailedEvent(BaseModel):
    event: Literal["response.failed"]
    error: ResponseFailedEventError | None = None


class ToolStartedEvent(BaseModel):
    event: Literal["tool.started"]
    run_id: str | None = None
    timestamp: float | None = None
    tool: str | None = None
    preview: str | None = None


class ToolCompletedEvent(BaseModel):
    event: Literal["tool.completed"]
    run_id: str | None = None
    timestamp: float | None = None
    tool: str | None = None
    duration: float | None = None
    error: bool | None = None


class ToolStartEvent(BaseModel):
    event: Literal["tool.start"]
    tool: str | None = None
    name: str | None = None
    call_id: str | None = None
    id: str | None = None
    input: dict[str, object] | None = None


class ToolProgressEvent(BaseModel):
    event: Literal["tool.progress", "hermes.tool.progress"]
    tool: str | None = None
    name: str | None = None
    call_id: str | None = None


class ToolResultEvent(BaseModel):
    event: Literal["tool.result"]
    call_id: str | None = None
    tool: str | None = None
    output: dict[str, object] | str | None = None
    result: str | None = None


class ReasoningEvent(BaseModel):
    event: Literal["reasoning.available", "response.reasoning", "hermes.reasoning"]
    text: str


class ApprovalRequestEvent(BaseModel):
    event: Literal["approval.request"]
    run_id: str | None = None
    timestamp: float | None = None
    command: str | None = None
    description: str | None = None
    pattern_key: str | None = None
    pattern_keys: list[str] | None = None
    choices: list[Literal["once", "session", "always", "deny"]] | None = None
    allow_permanent: bool | None = None
    smart_denied: bool | None = None


class ApprovalRespondedEvent(BaseModel):
    event: Literal["approval.responded"]
    run_id: str | None = None
    timestamp: float | None = None
    choice: Literal["once", "session", "always", "deny"] | None = None
    resolved: bool | None = None


class ApprovalRequiredEvent(BaseModel):
    event: Literal["approval.required", "hermes.approval_required"]
    run_id: str | None = None
    tool: str | None = None
    input: dict[str, object] | None = None
    session_id: str | None = None


class UsageEvent(BaseModel):
    event: Literal["hermes.usage"]
    input_tokens: int | None = None
    output_tokens: int | None = None
    total_tokens: int | None = None
    system_prompt_tokens: int | None = None
    model: str | None = None


class RunCompletedEvent(BaseModel):
    event: Literal["run.completed"]
    output: str | None = None
    usage: UsageInfo | None = None
    model: str | None = None
    session_id: str | None = None


class RunFailedEventErrorVariant1(BaseModel):
    message: str | None = None


class RunFailedEvent(BaseModel):
    event: Literal["run.failed"]
    error: RunFailedEventErrorVariant1 | str | None = None
    message: str | None = None


class RunCancelledEvent(BaseModel):
    event: Literal["run.cancelled"]
    run_id: str | None = None
    timestamp: float | None = None
    session_id: str | None = None


class ErrorEventErrorVariant1(BaseModel):
    message: str | None = None


class ErrorEvent(BaseModel):
    event: Literal["error"]
    error: ErrorEventErrorVariant1 | str | None = None
    message: str | None = None


class DoneEvent(BaseModel):
    event: Literal["done", "message_stop"]
    session_id: str | None = None
